source("tests/certification/helpers.R");source_r("mediation.R")
set.seed(401);n<-220;x<-rnorm(n);m<-.8*x+rnorm(n);y<-.3*x+1.1*m+rnorm(n);df<-data.frame(x=x,m=m,y=y)
r<-run_mediation_simple(df,"x","m","y",n_boot=1000,seed=77)
mm<-lm(m~x);my<-lm(y~x+m);mc<-lm(y~x)
expect_close(r$a,coef(mm)["x"]);expect_close(r$b,coef(my)["m"]);expect_close(r$c_direct,coef(my)["x"]);expect_close(r$c_total,coef(mc)["x"]);expect_close(r$indirect,coef(mm)["x"]*coef(my)["m"])
expect_true(isTRUE(r$total_effect_identity_ok)&&abs(r$total_effect_identity_error)<1e-8)
set.seed(77);vals<-rep(NA_real_,1000);for(i in 1:1000){ix<-sample.int(n,n,TRUE);vals[i]<-coef(lm(m[ix]~x[ix]))[2]*coef(lm(y[ix]~x[ix]+m[ix]))[3]};ci<-quantile(vals,c(.025,.975),type=6,names=FALSE);expect_close(c(r$ci_lower,r$ci_upper),ci)
expect_true(r$n_boot_valid==1000&&r$method=="bootstrap_percentile_type6")
cat("PASS mediación simple y bootstrap\n")
