source("tests/certification/helpers.R");source_r("helpers.R");source_r("statistics.R");source_r("instruments.R");require_pkg("psych");require_pkg("lavaan")
set.seed(501);n<-260;f1<-rnorm(n);f2<-.3*f1+sqrt(1-.3^2)*rnorm(n);D<-data.frame(a1=.8*f1+rnorm(n,.0,.6),a2=.75*f1+rnorm(n,.0,.65),a3=.7*f1+rnorm(n,.0,.7),b1=.82*f2+rnorm(n,.0,.55),b2=.76*f2+rnorm(n,.0,.65),b3=.72*f2+rnorm(n,.0,.7))
cr<-cronbach_alpha_ic(D[,1:3]);S<-cov(D[,1:3]);alpha<-3/2*(1-sum(diag(S))/sum(S));expect_close(cr$alpha_raw,alpha)
fa1<-factanal(D[,1:3],factors=1,rotation="none");lam1<-as.numeric(fa1$loadings);omega_ref<-sum(lam1)^2/(sum(lam1)^2+sum(fa1$uniquenesses));expect_close(cr$omega$omega_t_raw,omega_ref)
ca<-calc_cr_ave(c(.8,.7,.6));expect_close(ca$cr_raw,(2.1^2)/(2.1^2+sum(1-c(.8,.7,.6)^2)));expect_close(ca$ave_raw,mean(c(.8,.7,.6)^2))
mix<-calc_cr_ave(c(.8,-.7,.6));expect_true(isTRUE(mix$mixed_signs)&&mix$cr_raw<ca$cr_raw,"CR no debe ocultar signos mixtos")
afe<-compute_afe(D,n_factors=2,rotation="oblimin",estimator="minres");expect_true(is.null(afe$error)&&!isTRUE(afe$blocked));refa<-psych::fa(D,nfactors=2,rotate="oblimin",fm="minres");app_h2<-setNames(vapply(afe$loadings,`[[`,numeric(1),"h2"),vapply(afe$loadings,`[[`,character(1),"item"));expect_close(app_h2[names(refa$communality)],round(refa$communality,3),tol=.001)
vars<-list(list(name="F1",items=c("a1","a2","a3")),list(name="F2",items=c("b1","b2","b3")))
D_afc<-D;D_afc$unused_numeric<-NA_real_;afc<-compute_afc(D_afc,vars,"MLR");expect_true(is.null(afc$error)&&!isTRUE(afc$blocked)&&afc$n==n);fit<-lavaan::cfa('F1 =~ a1+a2+a3\nF2 =~ b1+b2+b3',data=D,estimator="MLR",std.lv=FALSE,missing="listwise");fi<-lavaan::fitMeasures(fit);pick<-function(a,b){v<-if(a%in%names(fi))as.numeric(fi[[a]])else NA_real_;if(!is.finite(v))v<-as.numeric(fi[[b]]);v};expect_close(afc$chi2_raw,pick("chisq.scaled","chisq"));expect_close(afc$p_value_raw,pick("pvalue.scaled","pvalue"));expect_close(afc$cfi,round(pick("cfi.robust","cfi"),3));expect_true(afc$fit_variant%in%c("robust_or_scaled","standard"))
ht<-compute_htmt(D,vars,n_boot=500,seed=88);cross<-abs(cor(D[,1:3],D[,4:6]));r1<-abs(cor(D[,1:3]));r2<-abs(cor(D[,4:6]));h<-mean(cross)/sqrt(mean(r1[upper.tri(r1)])*mean(r2[upper.tri(r2)]));expect_close(ht$pairs[[1]]$htmt,h);expect_true(ht$pairs[[1]]$bootstrap_valid>=400)
ratings<-matrix(c(4,5,4,5,4,4,3,4,4,4),nrow=2,byrow=TRUE);rownames(ratings)<-c("i1","i2");v<-compute_vaiken(ratings,5,5,1);expect_close(v$items[[1]]$V_raw,sum(ratings[1,]-1)/(5*4));expect_true(v$ci_status=="disabled_until_validated")
cat("PASS alfa, CR, AVE, AFE, AFC, HTMT y V de Aiken\n")
# Entradas inválidas de instrumento deben bloquearse antes de cualquier estimación.
cfg<-list(all_items=names(D),variables=vars,scale_min=1,scale_max=5,imputation="none")
bad_txt<-D;bad_txt$a1<-as.character(bad_txt$a1);bad_txt$a1[1]<-"texto";bt<-compute_instruments(bad_txt,cfg);expect_true(isTRUE(bt$blocked)&&bt$reason=="VALORES_NO_NUMERICOS")
bad_rng<-D;bad_rng$a1[1]<-99;br<-compute_instruments(bad_rng,cfg);expect_true(isTRUE(br$blocked)&&br$reason=="VALORES_FUERA_ESCALA")
cat("PASS bloqueo de valores no numéricos y fuera de escala\n")
